# Generated by Django 5.1.6 on 2025-02-21 16:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Fund ID')),
                ('name', models.CharField(max_length=255, verbose_name='Fund Name')),
                ('manager_name', models.CharField(max_length=255, verbose_name='Fund Manager Name')),
                ('description', models.TextField(default='', verbose_name='Fund Description')),
                ('nav', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Fund Net Asset Value')),
                ('performance', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Fund Performance(%)')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fund Date of Creation')),
            ],
        ),
    ]
